language: node_js
node_js:
  - "10"
os: linux
dist: xenial
arch: amd64
install:
  - yarn --frozen-lockfile
before_script:
  - npm install -g @tarojs/cli@2.1.5
script:
  - npm run build:component && npm publish
